### ISSUE TITLE
Attribute selectors containing css properties don't get properly highlighted

### ISSUE THREAD

**Issue by mattijsbliek** [cakebaker/scss-syntax.vim#43]
The following piece of css doesn't get properly highlighted. I suspect it's due to float: left being used inside the attribute selector.

```
.rich {
    .figure[style*="float:left"], .figure[style*="float: left"] { margin: 0 10px 10px 0; }
    .figure[style*="float:right"], .figure[style*="float: right"] { margin: 0 0 10px 10px; }
    .figure dd { @include font-size(14); }
}
```

Screenshot:
![screen shot 2014-07-08 at 17 33 28](https://cloud.githubusercontent.com/assets/2960795/3512052/6c476cac-06b5-11e4-843c-e311db0f6a3b.png)

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/eb6fb25ff38dcabf936ecf986eff5f5ff8fb3b36. Thanks for reporting!
