### ISSUE TITLE
foldmethod=syntax?

### ISSUE THREAD

**Issue by zanona** [cakebaker/scss-syntax.vim#46]
I am not sure if my installation isn't correct but when setting `foldmethod=syntax` I don't get any code folding? Is this a features present in the current release?

Thanks

**Comment by cakebaker** [comment]
I don't know whether code folding should work as I don't use code folding myself. It's possible that it's an issue with scss syntax. I can't test it right now as my computer is broken and the new one hasn't arrived yet :|

**Comment by cakebaker** [comment]
Ok, you were right, there wasn't any support for code folding. I added it in https://github.com/cakebaker/scss-syntax.vim/commit/74d6ddd78f572b63adc6dfb35e5ae9edc9af6b75. Thanks for reporting.

**Comment by ldong** [comment]
Add this one line to your `vimrc`

 `autocmd BufRead,BufNewFile *.css,*.scss,*.less setlocal foldmethod=marker foldmarker={,}`

Source: http://stackoverflow.com/questions/8671046/vim-folding-syntax-for-scss

**Comment by shmup** [comment]
@ldong that was the very first thing I tried, verifying my foldmethod was set to marker, and the .scss still wouldn't fold.

Then I tried this plugin, as @cakebaker points out the folding was added. Still no luck.

I'm certain I'll eventually get it sorted out, but just wanted to jot this experience down in the meantime.
