### ISSUE TITLE
@font-face breaks syntax highlighting

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#47]
When I try to use `@font-face` the syntax rules somehow break:
1. The parethesis don't match anymore
2. Some syntax, like `@each`, variables declarations, etc.. don't get highlighted anymore

The attachment illustrates the problem:
![scss syntax break](https://cloud.githubusercontent.com/assets/336957/6018178/0a34d844-ab95-11e4-8b26-77a7c989df75.jpg)

**Comment by cakebaker** [comment]
Hm, strange, your snippet works almost fine here (the <code>@font-face</code> statement is not highlighted), only if I move the <code>@font-face</code> block outside the mixin do I get the two issues you mention...

**Comment by cakebaker** [comment]
Ok, the issues I could reproduce are fixed and I hope these fixes also work for you. Thanks for reporting!

**Comment by alem0lars** [comment]
Thanks very much :+1:
