### ISSUE TITLE
Inside @function: @if breaks syntax hightlighting (and more directives)

### ISSUE THREAD

**Issue by joseluis** [cakebaker/scss-syntax.vim#48]
I have some functions with broken highlighting. I found out that's because of a nested `@if`.

`@if` syntax looks well inside mixins and by itself, but not inside a `@function`. Symptoms are the same as described in issue #47.

Also while inside a `@function` block more allowed directives doesn't get proper highlighting: `@error`,  `@warn`, `@for`,  `@each`, `@while`, `@debug`.

**Comment by cakebaker** [comment]
Fixed. Thanks for reporting!
