### ISSUE TITLE
@return not highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#49]
The directive `@return` isn't properly highlighted, as you can see in the screenshot below.

![screen shot 2015-02-20 at 10 36 16](https://cloud.githubusercontent.com/assets/336957/6284035/73d360f4-b8ec-11e4-935e-eb6dc6e9ecdc.png)

**Comment by joseluis** [comment]
Confirmed, it happens if nested. Also happens to `@debug`.

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/38e82819b458711be6c573525d2592af8f0c3336. Thanks for reporting!

**Comment by alem0lars** [comment]
Thanks for the excellent support :)
