### ISSUE TITLE
Some properties not highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#53]
Ok, without the `rainbow` plugin a lot of issues are gone.

Still there are some small issues, in particular some properties aren't highlighted.

As usual, I attach some screenshots..

![screen shot 2015-03-02 at 08 28 51](https://cloud.githubusercontent.com/assets/336957/6436920/6866cc1a-c0b7-11e4-9dda-89c543cb5394.png)
![screen shot 2015-03-02 at 08 29 23](https://cloud.githubusercontent.com/assets/336957/6436921/686c1148-c0b7-11e4-8fd3-470b07e34596.png)
![screen shot 2015-03-02 at 08 28 25](https://cloud.githubusercontent.com/assets/336957/6436922/68753fe8-c0b7-11e4-89bd-a059e04dbb1f.png)
![screen shot 2015-03-02 at 08 29 04](https://cloud.githubusercontent.com/assets/336957/6436923/68e303fc-c0b7-11e4-9953-b2cb31610ff4.png)

Thanks for the support :smile:

**Comment by cakebaker** [comment]
Ok, I can reproduce the issues. However, the issues in the second screenshot are CSS issues, i.e. you will also see them in CSS files:
* <code>hyphens</code> and <code>overflow-wrap</code> are not (yet) recognized by Vim's CSS syntax (you could use a plugin like https://github.com/hail2u/vim-css3-syntax to add CSS3 support)
* <code>listing</code>, <code>plaintext</code>, and <code>xmp</code> are obsolete elements you should no longer use (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/plaintext).

**Comment by alem0lars** [comment]
Ok,

I have tested with `vim-css3-syntax` and the new attributes (like `animate-*`) now works fine :smile: 

So the problems now should be:
* `map-merge` not highlighted: I think fixed in commit `8901b3b`. I will test the fix as soon as it's released
* classes inside pseudo-selectors, like `:not(.animate-once)`
* boolean keywords: `true` and `false`

Do you think that unquoted strings should be highlighted too (atm they aren't)?

Thanks for the awesome support,
Alessandro

**Comment by alem0lars** [comment]
FYI also logical operators like `not`, `or`, `and`, etc.. aren't highlighted

**Comment by cakebaker** [comment]
The issue with <code>map-merge</code> is fixed, however, there is a second issue in that snippet: the map used as parameter is not recognized.

Yes, I think unquoted strings should be highlighted.

**Comment by alem0lars** [comment]
Ok, I've tested the bugfixes and they work correctly :smile:  
I think the only missing bugfix is the one for classes inside pseudo-selectors:

![https://cloud.githubusercontent.com/assets/336957/6436922/68753fe8-c0b7-11e4-89bd-a059e04dbb1f.png](https://cloud.githubusercontent.com/assets/336957/6436922/68753fe8-c0b7-11e4-89bd-a059e04dbb1f.png)

**Comment by cakebaker** [comment]
I think all issues are fixed now. Thanks for reporting!
