### ISSUE TITLE
Some multiline selectors aren't highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#54]
As you can see in the screenshot below, the selectors inside the media query is correctly highlighted, but the selector outside in the media-query isn't correctly highlighted:

![screen shot 2015-03-02 at 18 31 10](https://cloud.githubusercontent.com/assets/336957/6446288/5d4b283c-c10a-11e4-82d6-bf283114cb7e.png)

Thanks

**Comment by cakebaker** [comment]
Ok, I can reproduce the issue.

**Comment by alem0lars** [comment]
Now it works correctly :+1: 

Thanks

**Comment by cakebaker** [comment]
No, this issue is not yet fixed, at least here I can still reproduce it.

**Comment by cakebaker** [comment]
Now it is fixed with https://github.com/cakebaker/scss-syntax.vim/commit/bd707a8099f3b4f62253f5c3e65d4155105c570c. Thanks for reporting!
