### ISSUE TITLE
Newline adds the starting symbol of the previous line

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#55]
I'm encountering a strange problem.
When the previous line starts with `>`, e.g. `> .information-element`, creating a new line starting from that line adds the character `>` at the beginning of the created line (in that example the created line has `>` instead of being empty).

![untitled](https://cloud.githubusercontent.com/assets/336957/6458906/5c790b70-c189-11e4-8266-fe21bd06e36b.png)

Is it a problem of this plugin?

Thanks

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/387dfd12b4bc348fdafdd45281d1de37ed260334. Thanks for reporting!
