### ISSUE TITLE
Variables declared inside media queries aren't highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#56]
If I try to declare a variable inside a media-query (`@media`), it's not highlighted.

I've attached a screenshot below, showing the problem: `$padding-horiz` isn't highlighted.

![screen shot 2015-03-04 at 10 37 50](https://cloud.githubusercontent.com/assets/336957/6481271/5075d3de-c25c-11e4-9e74-a1e08b7d48fc.png)

Thanks

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/07406cd7c24b770f25cbfe9c8726d2e9ce9b9aca. Thanks for reporting!

**Comment by alem0lars** [comment]
Now there is the same bug but when outside the media queries:

![screen shot 2015-03-05 at 10 29 49](https://cloud.githubusercontent.com/assets/336957/6502297/93430abc-c322-11e4-88c4-4f34dd0a1deb.png)

**Comment by cakebaker** [comment]
You already reported this issue in #54 ;-)
