### ISSUE TITLE
comments inside map and lists

### ISSUE THREAD

**Issue by joseluis** [cakebaker/scss-syntax.vim#57]
Comments are not highlighted when placed inside a multi-line map or list declaration.

```
$breakpoints: (
  wp-adminbar-mobile: 783px,  // comment not highlighted
  desktop: 60em,              /* comment not highlighted */
);
```

```
$list: "1",  /* comment not highlighted */
"2",         // comment not highlighted
"3"; 
```
NOTE: lists can also use braces: `$list: ( "1", "2" );`

EDIT: also a closing parentheses in the comment, is matched to the opening brace in the map / list.

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/4d331ce26dbf04c2044bc86098118823f3ff195f and https://github.com/cakebaker/scss-syntax.vim/commit/8fed47d78b48391cf699f4e94ee772a33f57f647. Thanks for reporting!
