### ISSUE TITLE
viewport units are not highlighted

### ISSUE THREAD

**Issue by joseluis** [cakebaker/scss-syntax.vim#58]
e.g.:
```
div {
  height: 1vh;
  max-height: 3vw;
  width: auto;
  max-width: 2vmin;
  min-width: 1vmax;
}
```

**Comment by cakebaker** [comment]
This is an issue with <code>css.vim</code> (on which the SCSS syntax file relies for the CSS stuff) and I opened a pull request there (https://github.com/JulesWang/css.vim/pull/52).

As a workaround you could also use a CSS3 plugin like https://github.com/hail2u/vim-css3-syntax
