### ISSUE TITLE
Some quoted strings inside lists aren't correctly highlighted

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#59]
The following screenshot shows the problem:
* `"body > .content"` isn't highlighted.

![screen shot 2015-03-24 at 09 27 59](https://cloud.githubusercontent.com/assets/336957/6797919/2a98967c-d208-11e4-8456-6b79bba99c96.png)

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/b9d71e63e4609e0dd9ba50c2682759e6f7fbbf2a. Thanks for reporting!
