### ISSUE TITLE
Mixin definition sometimes is not recognized

### ISSUE THREAD

**Issue by alem0lars** [cakebaker/scss-syntax.vim#61]
As you can see in the bottom of the screenshot the mixin definition syntax `@mixin ...` isn't recognized. Instead, it seems to be recognized as a function (!?)..

![screen shot 2015-03-25 at 08 45 18](https://cloud.githubusercontent.com/assets/336957/6820057/59c0a674-d2cb-11e4-9839-cf1a86e271fb.png)

Thanks

**Comment by cakebaker** [comment]
This issue is related to the second issue mentioned in #60 and with https://github.com/cakebaker/scss-syntax.vim/commit/be70ea8d205660b5fb67fd6a37b43d626b1ebe29 the issue has gone away, hence closing the ticket.
