### ISSUE TITLE
Liquid within SCSS string

### ISSUE THREAD

**Issue by MarioRicalde** [cakebaker/scss-syntax.vim#70]
I use liquid with scss, which means for `url("")` statements I use brackets. 

```
  background-image   : url("{{ 'neat-background-product.png' | asset_url }}");
```

the above breaks the highlighting.

Ideally it shouldn't really complaing about things within `""`.

Let me know if I can help with this one.

**Comment by cakebaker** [comment]
Thanks for reporting.

**Comment by MarioRicalde** [comment]
Thank you for fixing @cakebaker :)
